version: 4.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore
build:
  project: JustSaying.sln
  parallel: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal
test:
  assemblies: '**\*.UnitTests.dll'
artifacts:
- path: 'JustSaying.{version}*.nupkg'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/justsaying/api/v2/package
  api_key:
    secure: z9uSCdUVvor4vojIMrWmw0uJsFKmpTYPzk1GaWl0v8A3ArBODeClJoHme35QPnVp
  artifact: /.*nupkg/
  on:
    APPVEYOR_REPO_TAG: true
